### ISSUE TITLE
Filesize limitation workaround (and install issue)

### ISSUE THREAD

**Issue by devcortex0** [TobiasMarschner/ferrishare#8]
Hi, this is a just a small feature request - is it feasible to a client-side chunking of larger files? 2Gib limit defeats the purpose for me to set up this otherwise great project. Technically, if the binary data was just split into chunks and encrypted separately, it could even increase security (or integrity) I guess. 

I also tried to setup the dockerized container using these parameters
```
> Interface: 0.0.0.0:3000
> Proxy Depth: 1
> Admin password: ********
> Maximum filesize: 2G = 2147483648 Bytes
> Maximum storage: 6000G = 6442450944000 Bytes
> Maximum uploads per IP: 10
> Daily request limit per IP: 100
> Log level: INFO
> Enable Privacy Policy? Yes
> Enable Legal Notice? Yes
```

but am greeted with "404 page not found" if I access it over LAN on port 3000

docker compose file
```
services:
  # The FerriShare service (includes frontend, backend and database)
  ferrishare:
    # If you'd like to build FerriShare from source,
    # clone the repository and run 'docker compose build'.
    build: .
    # Otherwise, you can simply pull the prebuilt image from the
    # GitHub Container Registry by invoking 'docker compose pull'.
    image: ghcr.io/tobiasmarschner/ferrishare:1
    # Give the container a recognizable name, makes management easier.
    container_name: ferrishare
    restart: unless-stopped
    # All data for FerriShare resides in the '/app/data'-directory.
    # This includes:
    #   config.toml       => Configuration generated by '--init'-flag
    #   user_templates/*  => User-configurable templates
    #   sqlite.db         => Application database
    #   uploaded_files/*  => Encrypted files uploaded by users
    volumes:
      - "/mnt/thetank/data:/app/data"
    # This tells Traefik to make the `ferrishare` service accessible on localhost.
    # Refer to Traefik's documentation for more details on how to label and route services.
    labels:
      - "traefik.http.routers.ferrishare.rule=Host(`localhost`)"
  # The required reverse-proxy (refer to README for more details on why)
  # In this example we're using Traefik, but any reverse-proxy works.
  reverse-proxy:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    # Launch the reverse-proxy only after FerriShare is ready.
    depends_on:
      - ferrishare
    # Tells Traefik to automatically check Docker containers' labels.
    command:
      - "--providers.docker"
    # Bind's Traefik's default 'web' port (80) to port 3000 of the host machine.
    ports:
      - 3000:80
    # You have to pass through the docker socket so that Traefik can read the metadata
    # of the running `ferrishare` container and automatically establish the routes.
    volumes:
      # Rootful mode (default):
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Rootless mode:
      # - "/run/user/1000/docker.sock:/var/run/docker.sock:ro"
```

**Comment by TobiasMarschner** [comment]
> Hi, this is a just a small feature request - is it feasible to a client-side chunking of larger files? 2Gib limit defeats the purpose for me to set up this otherwise great project. Technically, if the binary data was just split into chunks and encrypted separately, it could even increase security (or integrity) I guess.

Acknowledged. I'm aware the 2GiB limit is rather small for the current day and age and this has bothered me since release, too.

Unfortunately, this isn't a small fix. I'd have to rearchitect parts of the backend to support storing and serving chunked assets, and would have to use a different cryptographic library and interface on the frontend.

Problem is that chunking is not just about splitting the plaintext into multiple parts and then encrypting those, the client must also verify that the order of the decryptable chunks it receives from the server has not been tampered with in the interim, otherwise the scheme isn't really *authenticated* anymore.

At that point it would be smarter for me to drop the browser's WebCrypto API and switch to libsodium, as it [offers a chunked encryption interface out-of-the-box](https://doc.libsodium.org/secret-key_cryptography/secretstream) and also has fewer footguns than the AES-GCM interface provided by WebCrypto.

I don't have a lot of time on my hands right now, so this isn't planned anytime soon, sorry.
It is something I would tackle for a 2.0 release down the line.

> I also tried to setup the dockerized container using these parameters
> 
> ```
> > Interface: 0.0.0.0:3000
> > Proxy Depth: 1
> > Admin password: ********
> > Maximum filesize: 2G = 2147483648 Bytes
> > Maximum storage: 6000G = 6442450944000 Bytes
> > Maximum uploads per IP: 10
> > Daily request limit per IP: 100
> > Log level: INFO
> > Enable Privacy Policy? Yes
> > Enable Legal Notice? Yes
> ```
> 
> but am greeted with "404 page not found" if I access it over LAN on port 3000
> 
> docker compose file
> 
> ```
> services:
>   # The FerriShare service (includes frontend, backend and database)
>   ferrishare:
>     # If you'd like to build FerriShare from source,
>     # clone the repository and run 'docker compose build'.
>     build: .
>     # Otherwise, you can simply pull the prebuilt image from the
>     # GitHub Container Registry by invoking 'docker compose pull'.
>     image: ghcr.io/tobiasmarschner/ferrishare:1
>     # Give the container a recognizable name, makes management easier.
>     container_name: ferrishare
>     restart: unless-stopped
>     # All data for FerriShare resides in the '/app/data'-directory.
>     # This includes:
>     #   config.toml       => Configuration generated by '--init'-flag
>     #   user_templates/*  => User-configurable templates
>     #   sqlite.db         => Application database
>     #   uploaded_files/*  => Encrypted files uploaded by users
>     volumes:
>       - "/mnt/thetank/data:/app/data"
>     # This tells Traefik to make the `ferrishare` service accessible on localhost.
>     # Refer to Traefik's documentation for more details on how to label and route services.
>     labels:
>       - "traefik.http.routers.ferrishare.rule=Host(`localhost`)"
>   # The required reverse-proxy (refer to README for more details on why)
>   # In this example we're using Traefik, but any reverse-proxy works.
>   reverse-proxy:
>     image: traefik
>     container_name: traefik
>     restart: unless-stopped
>     # Launch the reverse-proxy only after FerriShare is ready.
>     depends_on:
>       - ferrishare
>     # Tells Traefik to automatically check Docker containers' labels.
>     command:
>       - "--providers.docker"
>     # Bind's Traefik's default 'web' port (80) to port 3000 of the host machine.
>     ports:
>       - 3000:80
>     # You have to pass through the docker socket so that Traefik can read the metadata
>     # of the running `ferrishare` container and automatically establish the routes.
>     volumes:
>       # Rootful mode (default):
>       - "/var/run/docker.sock:/var/run/docker.sock:ro"
>       # Rootless mode:
>       # - "/run/user/1000/docker.sock:/var/run/docker.sock:ro"
> ```

I cannot replicate the issue on my end with those settings.
I want to point out one thing you said in particular, however:

> am greeted with "404 page not found" if I access it over LAN on port 3000

Remember, `localhost` as a hostname only exists on, well, `localhost`.
If you access the service via LAN I presume you enter something like `http://192.168.xxx.xxx:3000` in your browser to try and access the service, right?

At that point the hostname would be `192.168.xxx.xxx` and not `localhost` anymore, which means Traefik correctly responds with a 404. The rule you set up in the `docker-compose.yaml` instructs Traefik to only route to FerriShare when the request's hostname is `localhost`:
```yaml
services:
  ferrishare:
    ...
    labels:
      - "traefik.http.routers.ferrishare.rule=Host(`localhost`)"
```

If you don't want Traefik to do any routing / reverse-proxying and simply match any possible hostname, you could use the following rule:
```yaml
services:
  ferrishare:
    ...
    labels:
      - "traefik.http.routers.ferrishare.rule=HostRegexp(`.*`)"
```

You can find more info on how to set up routing rules in [Traefik's official documentation](https://doc.traefik.io/traefik/routing/routers/#rule).
